modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "karasunikilib"
version = "${version}"
displayName = "KarasunikiLib"
authors = "Hashibutogarasu"
description = '''
Library mod for Hashibutogarasu
'''
clientSideOnly = "${client_only}"
serverSideOnly = "${server_only}"
#logoFile = ""

[[dependencies.karasunikilib]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.karasunikilib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.karasunikilib]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "karasunikilib.mixins.json"
